# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cESBV_1Ri5ZA5_YbQddFblkjB9OW8geB
"""

import os
import pandas as pd

INFINITE_CSV = 'stock_rotation_infinite.csv'
TRADE_LOG_CSV = 'backtest_trades.csv'
DAILY_SUMMARY_CSV = 'backtest_summary.csv'

# 데이터가 없으면 종료
if not os.path.exists(INFINITE_CSV):
    print("아직 백테스트할 데이터가 없습니다.")
    exit()

df = pd.read_csv(INFINITE_CSV)
dates = sorted(df['날짜'].unique())

# 최소 20일치 데이터가 있어야 점수 계산이 가능
if len(dates) < 20:
    print(f"백테스트를 위한 데이터가 부족합니다. (현재 {len(dates)}일 / 최소 20일 필요)")
    exit()

# ----------------- 심플 백테스트 세팅 -----------------
portfolio = {}           # 현재 보유 주식
trade_history = []       # 사고 판 기록 (수익률 포함)
daily_summary = []       # 매일의 상태 (누적 수익률 등)
cumulative_yield = 0.0   # 총 누적 수익률(%) 단순 합산

# ----------------- 과거로 돌아가서 하루씩 시뮬레이션 -----------------
for i in range(19, len(dates)):
    current_date = dates[i]
    # 오늘을 포함한 최근 20일치 데이터만 자르기
    window_dates = dates[i-19 : i+1]
    df_window = df[df['날짜'].isin(window_dates)].copy()

    # 1. 점수 계산
    def calc_score(g):
        g['순위점수'] = (31 - g['순위']) * 2
        g['회전율등수'] = g['비율(%)'].rank(method='min', ascending=False)
        g['회전율점수'] = 31 - g['회전율등수']

        def penalty(row):
            base = row['순위점수'] + row['회전율점수']
            if row.get('등락률', 0) < 0:
                return -(base / 2)
            return base

        g['일별점수'] = g.apply(penalty, axis=1)
        return g

    df_window = df_window.groupby('날짜', group_keys=False).apply(calc_score)

    # 20일 누적 총점수 계산
    summary = df_window.groupby('종목명').agg(총점수=('일별점수', 'sum')).reset_index()
    summary = summary.sort_values(by='총점수', ascending=False).reset_index(drop=True)

    # 오늘 기준 5등 이내, 10등 이내 종목 리스트 뽑기
    top5_stocks = summary.head(5)['종목명'].tolist()
    top10_stocks = summary.head(10)['종목명'].tolist()

    # 해당 기간의 마지막 확인된 가격 정보 (매수/매도를 위한 가격표)
    last_prices = df_window.drop_duplicates(subset=['종목명'], keep='last').set_index('종목명')['현재가'].to_dict()

    # ----------------- 매도 로직 (10위 밖으로 밀려나면 판다) -----------------
    for stock in list(portfolio.keys()):
        if stock not in top10_stocks:
            sell_price = last_prices.get(stock, portfolio[stock]['buy_price'])
            buy_price = portfolio[stock]['buy_price']

            # 순수 수익률(%) 계산 및 누적
            yield_pct = ((sell_price - buy_price) / buy_price) * 100
            cumulative_yield += yield_pct

            trade_history.append({
                '날짜': current_date,
                '종목명': stock,
                '행동': '매도(SELL)',
                '체결가': sell_price,
                '수익률(%)': round(yield_pct, 2)
            })
            del portfolio[stock] # 포트폴리오에서 비우기

    # ----------------- 매수 로직 (5위 안에 새로 들어오면 무조건 산다) -----------------
    for stock in top5_stocks:
        if stock not in portfolio and stock in last_prices:
            buy_price = last_prices[stock]
            portfolio[stock] = {'buy_price': buy_price, 'buy_date': current_date}

            trade_history.append({
                '날짜': current_date,
                '종목명': stock,
                '행동': '매수(BUY)',
                '체결가': buy_price,
                '수익률(%)': 0.0
            })

    # ----------------- 일별 요약 기록 (불필요한 보유종목 정보 삭제) -----------------
    daily_summary.append({
        '날짜': current_date,
        '누적수익률(%)': round(cumulative_yield, 2)
    })

# ----------------- 결과 파일 저장 -----------------
if trade_history:
    pd.DataFrame(trade_history).to_csv(TRADE_LOG_CSV, index=False, encoding='utf-8-sig')
if daily_summary:
    pd.DataFrame(daily_summary).to_csv(DAILY_SUMMARY_CSV, index=False, encoding='utf-8-sig')

print("✅ 심플 백테스트 완료! 매매기록과 날짜별 누적 수익률이 CSV로 저장되었습니다.")